namespace: "default"
fineract:
  DFSPIDS: ""
  SPRING_PROFILES_ACTIVE: "bb"
  image: "us.icr.io/phee-ns/fineract:latest"
  ingress:
    enabled: false
    hostname: ""
    annotations: 
      kubernetes.io/ingress.class: "nginx"
  javaopts: "-Xms1G -Xmx1700m"
  resources:
    limits:
      cpu: "1000m"
      memory: "8Gi"
    requests:
      cpu: "200m"
      memory: "8Gi"

communityapp:
  image: "openmf/community-app:latest"
  ingress:
    enabled: false
    hostname: ""
    path: "/community"
    annotations: 
      kubernetes.io/ingress.class: "nginx"

webapp:
  image: "us.icr.io/phee-ns/web-app:latest"
  ingress:
    enabled: false
    hostname: ""
    path: "/web"
    annotations: 
      kubernetes.io/ingress.class: "nginx"

selfservice:
  image: "us.icr.io/phee-ns/web-self-service-app:latest"
  ingress:
    enabled: false
    hostname: ""
    path: "/self"
    annotations: 
      kubernetes.io/ingress.class: "nginx"




mysql:
  image:
    tag: "10.5.15-debian-10-r0"
    debug: true
  auth:
    username: "mifos"
    password: "password"
    rootPassword: "4ET6ywqlGt"
  initdbScripts:
    setup.sql: |-
      # create databases
      CREATE DATABASE IF NOT EXISTS `fineract_tenants`;
      CREATE DATABASE IF NOT EXISTS `fineract_default`;
      # create root user and grant rights
      GRANT ALL ON *.* TO 'root'@'%';
      GRANT ALL PRIVILEGES ON `fineract_tenants`.* TO 'mifos';
      GRANT ALL PRIVILEGES ON `fineract_default`.* TO 'mifos';
  primary:
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"

wildcardhostname: ""

tls: ""  