fin-engine:
  fineract:
    DFSPIDS: "rhino,gorilla"
    ingress:
      enabled: true
      hostname: "rhino.mifos.g2pconnect.io"
      wildcardhostname: "rhino.mifos.g2pconnect.io"
    resources:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "0.5Gi"

  fineract1:
    DFSPIDS: "rhino,gorilla"
    ingress:
      enabled: true
      hostname: "gorilla.mifos.g2pconnect.io"
      wildcardhostname: "gorilla.mifos.g2pconnect.io"
    resources:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "0.5Gi"      

  communityapp:
    enabled: true
    ingress:
      enabled: true
      hostname: "communityapp.mifos.g2pconnect.io"
      wildcardhostname: "communityapp.mifos.g2pconnect.io"

  webapp:
    ingress:
      enabled: false
      hostname: "webapp.mifos.g2pconnect.io"
