apiVersion: v1
appVersion: "1.0"
description: Fineract Engine
name: fin-engine
version: 1.0.0-SNAPSHOT
dependencies:
- name: mysql
  version: 8.8.26
  repository: "https://charts.bitnami.com/bitnami"
  alias: mysql

