fineract:
  DFSPIDS: ""
  SPRING_PROFILES_ACTIVE: "bb"
  image: "us.icr.io/phee-ns/fineract:fineract-enabled-pentaho"
  ingress:
    enabled: true
    api: networking.k8s.io/v1beta1
    hostname: "fin.ibank.financial"
    annotations: 
      kubernetes.io/ingress.class: "nginx"
    backend:
      serviceName: fineract
      servicePort: 80


mysql:
  fullnameOverride: "fineractmysql"
  image:
    tag: "5.7.37"
    debug: true
  auth:
    username: "mifos"
    password: "password"
    rootPassword: "4ET6ywqlGt"
  initdbScripts:
    setup.sql: |-
      # create databases
      CREATE DATABASE IF NOT EXISTS `fineract_tenants`;
      CREATE DATABASE IF NOT EXISTS `fineract_default`;
      # create root user and grant rights
      GRANT ALL ON *.* TO 'root'@'%';
      GRANT ALL PRIVILEGES ON `fineract_tenants`.* TO 'mifos';
      GRANT ALL PRIVILEGES ON `fineract_default`.* TO 'mifos';
  primary:
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"

wildcardhostname: "*.ibank.financial"

tls: "ibank"  